spring:
  application:
    name: danang-safefood-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/danang_safefood
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  sql:
    init:
      mode: never                 # ← Quan trọng: always để chạy data.sql
      encoding: UTF-8
      continue-on-error: false
      separator: ;

server:
  port: 8080

jwt:
  # Base64 secret (>= 256-bit). Example generate:
  #  - PowerShell: [Convert]::ToBase64String((1..32 | ForEach-Object {Get-Random -Maximum 256}))
  secret: "DaNangSafeFood2026SuperSecretKeyForJWTAuthentication1234567890"
  access-token-expiration-ms: 900000     # 15 minutes
  refresh-token-expiration-ms: 604800000 # 7 days