spring:
  application:
    name: danang-safefood-backend

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://localhost:5432/danang_safe_food
    username: root
    password: 123456
#    mail sender configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: vndhieu05@gmail.com
    password: duzq ufne rbjo obav
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  sql:
    init:
      mode: never # ← Quan trọng: always để chạy data.sql
      encoding: UTF-8
      continue-on-error: false
      separator: ;

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

jwt:
  # Base64 secret (>= 256-bit). Example generate:
  #  - PowerShell: [Convert]::ToBase64String((1..32 | ForEach-Object {Get-Random -Maximum 256}))
  secret: "DaNangSafeFood2026SuperSecretKeyForJWTAuthentication1234567890"
  access-token-expiration-ms: 900000 # 15 minutes
  refresh-token-expiration-ms: 604800000 # 7 days
