spring:
  application:
    name: danang-safefood-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/danang_safefood
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  # Base64 secret (>= 256-bit). Example generate:
  #  - PowerShell: [Convert]::ToBase64String((1..32 | ForEach-Object {Get-Random -Maximum 256}))
  secret: "DaNangSafeFood2026SuperSecretKeyForJWTAuthentication1234567890"
  access-token-expiration-ms: 900000     # 15 minutes
  refresh-token-expiration-ms: 604800000 # 7 days